feat: extend config file to support other options
sassoftware/gotagger pull request #60
Opened 2022-03-22 16:31 UTC by wfscheper

This expands the set of options covered by the `gotagger.json` config
file. A side-effect of expanding how the config file is parsed,
the restriction on how "release" commits increment the version was
moved from parsing to enforcement by `Table.Get`.

Fixes #56

2022-03-22 19:16 UTC, ninjamast3r requested changes
Concerns are mostly grammatical.

2022-03-22 19:16 UTC, ninjamast3r commented on config.go
> +// ParseJSON unmarshals a byte slic containing mappings of commit type to semver increment. Mappings determine
slice

2022-03-22 20:48 UTC, wfscheper commented on README.md
> +Allowed values are "major", "minor", "patch", and "none".
Whoops, yeah I think you're right...

2022-03-22 20:49 UTC, wfscheper commented on README.md
> +Allowed values are "major", "minor", "patch", and "none".
Probably. I just C&P from above. I'll check this one too.

2022-05-02 18:21 UTC, wfscheper commented on README.md
> +Allowed values are "major", "minor", "patch", and "none".
Fixed, dropped "major".

2022-05-02 18:21 UTC, wfscheper commented on README.md
> +Allowed values are "major", "minor", "patch", and "none".
Fixed, dropped "major".

2022-05-02 18:21 UTC, wfscheper commented on README.md
> +controls which part of the sematic version
Done

2022-05-02 18:21 UTC, wfscheper commented on config.go
> +// ParseJSON unmarshals a byte slic containing mappings of commit type to semver increment. Mappings determine
Done.

2022-05-02 18:31 UTC, wfscheper commented on README.md
> +controls which modules gotagger will atempt to version.
Done.

2022-06-13 17:50 UTC, ninjamast3r approved these changes

2022-06-21 17:12 UTC, merged